// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDB;

namespace MyDB.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20220227133604_v1.5")]
    partial class v15
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainDTO.EFModels.Annual_details", b =>
                {
                    b.Property<int>("Annual_Did")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Annual_April")
                        .HasColumnType("int");

                    b.Property<int>("Annual_August")
                        .HasColumnType("int");

                    b.Property<int>("Annual_December")
                        .HasColumnType("int");

                    b.Property<int>("Annual_February")
                        .HasColumnType("int");

                    b.Property<int>("Annual_January")
                        .HasColumnType("int");

                    b.Property<int>("Annual_July")
                        .HasColumnType("int");

                    b.Property<int>("Annual_June")
                        .HasColumnType("int");

                    b.Property<int>("Annual_November")
                        .HasColumnType("int");

                    b.Property<int>("Annual_October")
                        .HasColumnType("int");

                    b.Property<int>("Annual_September")
                        .HasColumnType("int");

                    b.Property<int>("Annual_combined")
                        .HasColumnType("int");

                    b.Property<string>("Annual_existing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Annual_jobs")
                        .HasColumnType("int");

                    b.Property<int>("Annual_march")
                        .HasColumnType("int");

                    b.Property<int>("Annual_may")
                        .HasColumnType("int");

                    b.Property<string>("Annual_note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Annual_Did");

                    b.ToTable("Annual_details");
                });

            modelBuilder.Entity("DomainDTO.EFModels.Annual_information", b =>
                {
                    b.Property<int>("Annual_Fid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Annual_detailsDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TAB_department")
                        .HasColumnType("int");

                    b.Property<string>("TAB_people")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TAB_time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TAB_year")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Annual_Fid");

                    b.ToTable("Annual_information");
                });
#pragma warning restore 612, 618
        }
    }
}
