// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDB;

namespace MyDB.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20220301101813_V1.58")]
    partial class V158
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainDTO.EFModels.MInsurance", b =>
                {
                    b.Property<int>("car_AId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("car_Handler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("car_Insurance")
                        .HasColumnType("datetime2");

                    b.Property<string>("car_Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("car_Tabulation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("car_end")
                        .HasColumnType("datetime2");

                    b.Property<string>("car_money")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("car_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("car_passenger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("car_project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("car_purchase")
                        .HasColumnType("datetime2");

                    b.Property<int>("car_seat")
                        .HasColumnType("int");

                    b.Property<DateTime>("car_strat")
                        .HasColumnType("datetime2");

                    b.HasKey("car_AId");

                    b.ToTable("mInsurances");
                });

            modelBuilder.Entity("DomainDTO.EFModels.MViolation", b =>
                {
                    b.Property<int>("DId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Handler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Violation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("drive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("handle")
                        .HasColumnType("datetime2");

                    b.Property<string>("money")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("points")
                        .HasColumnType("int");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("time")
                        .HasColumnType("datetime2");

                    b.HasKey("DId");

                    b.ToTable("mViolations");
                });

            modelBuilder.Entity("DomainDTO.EFModels.Maintain", b =>
                {
                    b.Property<int>("vehicle_BId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("vehicle_Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicle_Handler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicle_Kilometers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicle_cost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("vehicle_datime")
                        .HasColumnType("datetime2");

                    b.Property<string>("vehicle_project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicle_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicle_remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vehicle_BId");

                    b.ToTable("maintains");
                });

            modelBuilder.Entity("DomainDTO.EFModels.Mrepair", b =>
                {
                    b.Property<int>("CId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Handler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kilometers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("fault")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("time")
                        .HasColumnType("datetime2");

                    b.HasKey("CId");

                    b.ToTable("mrepairs");
                });
#pragma warning restore 612, 618
        }
    }
}
