// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDB;

namespace MyDB.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20220302020130_v5.6")]
    partial class v56
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainDTO.EFModels.MeetingRoomNew", b =>
                {
                    b.Property<int>("MeetingRoom_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MeetingRoom_Administrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_Capacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_Floor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_OrAirConditioner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_OrNetwork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_OrNetworkRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_OrProjector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_OrWaterDispenser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_OrWhiteboard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_Seat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MeetingRoom_Id");

                    b.ToTable("MeetingRoomNew");
                });

            modelBuilder.Entity("DomainDTO.EFModels.ProcurementDetails", b =>
                {
                    b.Property<int>("Goods_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Goods_Money")
                        .HasColumnType("real");

                    b.Property<string>("Goods_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goods_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Goods_Num")
                        .HasColumnType("int");

                    b.Property<float>("Goods_Price")
                        .HasColumnType("real");

                    b.Property<string>("Goods_Specifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goods_Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Goods_Id");

                    b.ToTable("ProcurementDetails");
                });

            modelBuilder.Entity("DomainDTO.EFModels.ProcurementManagement", b =>
                {
                    b.Property<int>("Management_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Management_Money")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Management_Name")
                        .HasColumnType("int");

                    b.Property<string>("Management_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Management_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Management_Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Management_Specifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Management_Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Management_Id");

                    b.ToTable("ProcurementManagement");
                });

            modelBuilder.Entity("DomainDTO.EFModels.Reception", b =>
                {
                    b.Property<int>("Reception_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Reception_Applicant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_ApplyTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_BeginResidenceTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_Flight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_GuestName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_GuestUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_OrData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_OrItems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_OtherRequirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_OverResidenceTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_Unawares")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Reception_Id");

                    b.ToTable("Reception");
                });

            modelBuilder.Entity("DomainDTO.EFModels.ReceptionItemsDetails", b =>
                {
                    b.Property<int>("Items_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Items_InventoryQuantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Items_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Items_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Items_NumberRemaining")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Items_Specifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Items_UseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Items_Id");

                    b.ToTable("ReceptionItemsDetails");
                });

            modelBuilder.Entity("DomainDTO.EFModels.ReceptionTripDetails", b =>
                {
                    b.Property<int>("Trip_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("Trip_AccompanyingOfficials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trip_BeginTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trip_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trip_OrCar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trip_OrHall")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trip_OrMeal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trip_OrReservationHotel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trip_OrReservationMeetingRoom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trip_OverTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trip_ParticipateDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trip_Trip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Trip_Id");

                    b.ToTable("ReceptionTripDetails");
                });

            modelBuilder.Entity("DomainDTO.EFModels.ReservationMeetingRoom", b =>
                {
                    b.Property<int>("Reservation_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Reservation_BeginTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reservation_MeetingRoom")
                        .HasColumnType("int");

                    b.Property<string>("Reservation_OverTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reservation_Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reservation_Seat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reservation_UseDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reservation_Users")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Reservation_Id");

                    b.ToTable("ReservationMeetingRoom");
                });
#pragma warning restore 612, 618
        }
    }
}
