// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDB;

namespace MyDB.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20220225030037_v1.2")]
    partial class v12
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainDTO.EFModels.BPMSysUsers", b =>
                {
                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("CostCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateHired")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HRID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogonProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameSpell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Office")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SysUser")
                        .HasColumnType("bit");

                    b.Property<int>("UserLevel")
                        .HasColumnType("int");

                    b.Property<string>("WWWHomePage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("家庭电话")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Account");

                    b.ToTable("BPMSysUsers");
                });

            modelBuilder.Entity("DomainDTO.EFModels.Employed", b =>
                {
                    b.Property<int>("Employed_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmployedEntry_JobName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employed_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employed_Categary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employed_Culture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Employed_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Employed_Department")
                        .HasColumnType("int");

                    b.Property<string>("Employed_Health")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employed_Instruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employed_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employed_Relative")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Employed_Sex")
                        .HasColumnType("bit");

                    b.Property<string>("Employed_Specialty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employed_Thetrial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employed_Timelimit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Employed_Treatment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Employed_Year")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Employed_Id");

                    b.ToTable("Employed");
                });

            modelBuilder.Entity("DomainDTO.EFModels.Relative", b =>
                {
                    b.Property<int>("Relative_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Relative_Between")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relative_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relative_Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Relative_Id");

                    b.ToTable("Relative");
                });
#pragma warning restore 612, 618
        }
    }
}
