// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDB;

namespace MyDB.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20220302112824_v6.3")]
    partial class v63
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainDTO.EFModels.CarApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CarUseStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CarUse_AccPeople")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarUse_ApplyDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarUse_Approach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CarUse_BackTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CarUse_CarID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarUse_Cause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarUse_Demt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarUse_Driver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarUse_EndKM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarUse_EndSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarUse_PeopleNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarUse_Proposer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarUse_RealKM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarUse_Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarUse_StartKM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarUse_StartSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CarUse_StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CarUse_Week")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CarApplication");
                });

            modelBuilder.Entity("DomainDTO.EFModels.Departure", b =>
                {
                    b.Property<int>("Departure_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Departure_Applicant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Departure_Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Departure_Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Departure_Entry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Departure_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departure_Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Departure_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Departure_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departure_Why")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Departure_Id");

                    b.ToTable("Departure");
                });

            modelBuilder.Entity("DomainDTO.EFModels.DeparturetTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dt_AdminCase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dt_AdminContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dt_ApplyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dt_Certify")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dt_Demt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dt_DemtCase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dt_DemtContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dt_Files")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dt_FinanceCase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dt_FinanceContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dt_Heir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dt_Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dt_Proposer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dt_Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DeparturetTransfer");
                });

            modelBuilder.Entity("DomainDTO.EFModels.ExitInterview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Exit_AwardsAndRecognition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit_CommunicationChannels")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit_CommunicationWithManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit_CompanyManagement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit_Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit_Demt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit_Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit_EntryData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit_InterviewRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit_IsHire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit_Job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit_JobSatisfaction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit_LeaveCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit_LeaveData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit_PromotionProspects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit_SalaryAndBenefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit_StaffID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit_StaffName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit_TermCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit_TermType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit_TrainingAndDevelopment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exit_lister")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExitInterview");
                });

            modelBuilder.Entity("DomainDTO.EFModels.Leave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Leave_AffixName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Leave_Day")
                        .HasColumnType("int");

                    b.Property<string>("Leave_Demo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Leave_EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Leave_LeaveType")
                        .HasColumnType("int");

                    b.Property<string>("Leave_Proposer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leave_Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leave_Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Leave_StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Leave_Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Leave");
                });

            modelBuilder.Entity("DomainDTO.EFModels.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Leave_TypeId")
                        .HasColumnType("int");

                    b.Property<string>("Leave_TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeaveType");
                });

            modelBuilder.Entity("DomainDTO.EFModels.MeetingRoomNew", b =>
                {
                    b.Property<int>("MeetingRoom_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MeetingRoom_Administrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_Capacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_Floor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_OrAirConditioner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_OrNetwork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_OrNetworkRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_OrProjector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_OrWaterDispenser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_OrWhiteboard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingRoom_Seat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MeetingRoom_Id");

                    b.ToTable("MeetingRoomNew");
                });

            modelBuilder.Entity("DomainDTO.EFModels.Procurement", b =>
                {
                    b.Property<int>("Procurement_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Procurement_Agent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Procurement_Applicant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Procurement_ApplyDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Procurement_ApplyTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Procurement_HandlingDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Procurement_HandlingTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Procurement_Use")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Procurement_Id");

                    b.ToTable("Procurement");
                });

            modelBuilder.Entity("DomainDTO.EFModels.ProcurementDetails", b =>
                {
                    b.Property<int>("Goods_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Goods_Money")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goods_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goods_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goods_Num")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goods_Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goods_Specifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goods_Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Goods_Id");

                    b.ToTable("ProcurementDetails");
                });

            modelBuilder.Entity("DomainDTO.EFModels.Reception", b =>
                {
                    b.Property<int>("Reception_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Reception_Applicant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_ApplyTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_BeginResidenceTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_Flight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_GuestName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_GuestUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_OrData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_OrItems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_OtherRequirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_OverResidenceTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reception_Unawares")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Reception_Id");

                    b.ToTable("Reception");
                });

            modelBuilder.Entity("DomainDTO.EFModels.ReceptionItemsDetails", b =>
                {
                    b.Property<int>("Items_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Items_InventoryQuantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Items_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Items_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Items_NumberRemaining")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Items_Specifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Items_UseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Items_Id");

                    b.ToTable("ReceptionItemsDetails");
                });

            modelBuilder.Entity("DomainDTO.EFModels.ReceptionTripDetails", b =>
                {
                    b.Property<int>("Trip_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("Trip_AccompanyingOfficials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trip_BeginTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trip_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trip_OrCar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trip_OrHall")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trip_OrMeal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trip_OrReservationHotel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trip_OrReservationMeetingRoom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trip_OverTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trip_ParticipateDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trip_Trip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Trip_Id");

                    b.ToTable("ReceptionTripDetails");
                });

            modelBuilder.Entity("DomainDTO.EFModels.ReservationMeetingRoom", b =>
                {
                    b.Property<int>("Reservation_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Reservation_BeginTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reservation_MeetingRoom")
                        .HasColumnType("int");

                    b.Property<string>("Reservation_OverTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reservation_Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reservation_Seat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reservation_UseDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reservation_Users")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Reservation_Id");

                    b.ToTable("ReservationMeetingRoom");
                });
#pragma warning restore 612, 618
        }
    }
}
