// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDB;

namespace MyDB.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20220228004045_V1.691")]
    partial class V1691
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainDTO.EFModels.Resources", b =>
                {
                    b.Property<int>("staff_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("staff_Culture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_Salary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("staff_age")
                        .HasColumnType("int");

                    b.Property<string>("staff_application")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_contract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_enclosure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("staff_existing")
                        .HasColumnType("int");

                    b.Property<string>("staff_explain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_other")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_post")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("staff_probation")
                        .HasColumnType("datetime2");

                    b.Property<int>("staff_recruit")
                        .HasColumnType("int");

                    b.Property<string>("staff_remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("staff_time")
                        .HasColumnType("datetime2");

                    b.HasKey("staff_Id");

                    b.ToTable("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
